### ISSUE TITLE
normalizr for mutations?

### ISSUE THREAD

**Issue by matthewmueller** [julienvincent/modelizr#1]
hey this is a cool library, i'm starting to think about the same thing.

I was wondering if you thought about using normalizr going the other way for mutations. Something like this:

**mutation:**

```js
user.create({
  name: 'matt',
  notes: [
    {
      id: 123,
      title: 'blah',
      body: 'hi'
    }
  ]
})
```

**normalized:**

```js
entities: {
  users: [
    {
    name: 'matt',
    notes: [1]
    }
  ],
  notes: [
    {
      id: 123,
      title: 'blah',
      body: 'hi'
    }
  ]
}
```

**database inserts:**

```sql
INSERT INTO users VALUES (...)
INSERT INTO notes VALUES (...)
```

any downsides you foresee with this approach?

**Comment by julienvincent** [comment]
I'm not quite sure what you are proposing. What it seems to me is you are trying to create a model and a mutation at the same time?
