### ISSUE TITLE
Generalise Queries

### ISSUE THREAD

**Issue by alexisvincent** [julienvincent/modelizr#3]
I noticed that the current implementation assumes root level queries ```query``` and ```mutation``` (I think?). Please note that while this probably how most people are using graphql, modeller shouldn't make any assumptions about user top level queries. 

A top level query can have the following example forms (Again, I'm pretty sure this is how it works):
```graphql
query Alias {}
someThing Thingie {}
mutation lol {}
```

Users should be able to specify the top level exposed name and the specific query alias. Also, mutations are functionally equivalent to queries. The only difference is convention.

**Comment by julienvincent** [comment]
I'm pretty sure GraphQL's spec defines mutations as `mutation someName`. You are able to modify `someName` using a `.as()` modifier.

**Comment by julienvincent** [comment]
Need to check up on the spec though.

**Comment by alexisvincent** [comment]
You're right, checkout [2.3](http://facebook.github.io/graphql/#sec-Language.Operations)
